### ISSUE TITLE
Window width bug

### ISSUE THREAD

**Issue by liaprins-czi** [napari/product-heuristics-2020#35] opened 2020-10-12 23:46 UTC
In adjusting the size of the console, one can drag the space over the other windows, without responsively resizing (this doesn't always occur, sometimes window is responsive).
__________________________________________________________
**Recommendation**

Fix so the window behaves responsibly.

Minor issue
○○○   No design work
▼▼▼   High development work

<img width="1278" alt="resizebug" src="https://user-images.githubusercontent.com/53277128/95920648-a02b1200-0d64-11eb-82f6-40026a162293.png">

**Comment by sofroniewn** [comment] 2020-10-17 22:55
I was just able to reproduce this on https://github.com/napari/napari/commit/f8f61733c0d7f0b1781abd5da7a8d5f5dc8539af. I was fiddling with the size of the console and all of a sudden it happened, very disconcerting.

<img width="1171" alt="Screen Shot 2020-10-17 at 3 53 42 PM" src="https://user-images.githubusercontent.com/6531703/96354938-1a270800-1091-11eb-8a6d-10b3344ecfc3.png">

**Comment by liu-ziyang** [comment] 2020-10-19 21:56
This issue is scheduled for our Oct 20th - Nov 2nd Sprint

**Comment by liu-ziyang** [comment] 2020-10-23 20:45
so far I am not able to reproduce, however somehow my console doesn't seem to be working at all: 
```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/console_widget.py", line 427, in eventFilter
    return self._event_filter_console_keypress(event)
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/frontend_widget.py", line 339, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/console_widget.py", line 1245, in _event_filter_console_keypress
    self.execute(interactive = not shift_down)
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/console_widget.py", line 653, in execute
    self.do_execute(source, True, '')
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/history_console_widget.py", line 43, in do_execute
    super(HistoryConsoleWidget, self).do_execute(source, complete, indent)
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/console_widget.py", line 663, in do_execute
    self._execute(source, False)
  File "/Users/zliu/PycharmProjects/napari/venv/lib/python3.8/site-packages/qtconsole/frontend_widget.py", line 250, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'
```

**Comment by sofroniewn** [comment] 2020-10-23 20:48
> AttributeError: 'NoneType' object has no attribute 'execute'

Thats no good!

**Comment by liu-ziyang** [comment] 2020-10-23 21:49
I am turning into the bundled app to try to reproduce this, and unfortunately, I found our 0.3.8 is failing to build for macOS 😢, so I am using an earlier build of the bundled app to reproduce this, so far I found the console is responsive to other component and that despite I try to create edge cases by moving widget in and out, adjusting window size, and adjust console size, I cannot reproduce the reported behavior. Going to tag the issue to get more help

**Comment by sofroniewn** [comment] 2020-10-23 23:01
@ziyangczi the build did work for `0.3.8rc2` see https://github.com/napari/napari/releases/tag/v0.3.8rc2, but i think this bug is not fixed by anything. not sure i really understand it yet

**Comment by liu-ziyang** [comment] 2020-10-27 21:28
@napari/core-devs sorry to ping all, has anyone experienced this before? is there anything that you can recall that might lead to this?

**Comment by sofroniewn** [comment] 2020-10-27 21:46
> @napari/core-devs sorry to ping all, has anyone experienced this before? is there anything that you can recall that might lead to this?

I cannot reproduce this at will. It just happened to me, and I thought, ah perfect, I'll record it for you, but now I can't make it happen again :-( Will keep on trying, but it seemed to me to happen when I moved the mouse very quickly ...

**Comment by GenevieveBuckley** [comment] 2020-10-27 22:24
No I can't reproduce this at all, sorry

**Comment by liu-ziyang** [comment] 2020-11-02 19:09
closing this issue for now due to reproducing issue

**Closed as completed by liu-ziyang** 2020-11-02 19:09 UTC
Labels: napari app, broken functionality, UI bug, need to reproduce, not fixed
